parameters:
  # Required
  - name: "ENV_FILE"
    type: string
  - name: "API_TEST_FILE"
    type: string
  - name: "REPORT_FILE_NAME_PREFIX"
    type: string
  - name: 'TEST_DISPLAY_NAME'
    type: string
steps:
  - script: |
      yarn global add newman
    displayName: 'Newman installation'
  - script: |
      newman run ${{ parameters.API_TEST_FILE }} -e ${{ parameters.ENV_FILE }} --ignore-redirects --reporters cli,junit --reporter-junit-export Results/${{ parameters.REPORT_FILE_NAME_PREFIX }}-api-TEST.xml
    displayName: ${{ parameters.TEST_DISPLAY_NAME }}
  - task: PublishTestResults@2
    condition: succeededOrFailed()
    inputs:
      testResultsFormat: 'JUnit'
      testResultsFiles: '**/${{ parameters.REPORT_FILE_NAME_PREFIX }}-api-TEST.xml'
      searchFolder: '$(System.DefaultWorkingDirectory)'