apiVersion: v2
name: pagopa-qi-fdr-kpi-service
description: Microservice that handles KPI for FDR
type: application
version: 1.2.0
appVersion: 1.2.0
dependencies:
  - name: microservice-chart
    version: 7.5.0
    repository: "https://pagopa.github.io/aks-microservice-chart-blueprint"
