apiVersion: v2
name: pagopa-qi-fdr-kpi-service
description: Microservice that handles KPI for FDR
type: application
version: 0.3.1
appVersion: 0.3.0
dependencies:
  - name: microservice-chart
    version: 2.3.1
    repository: "https://pagopa.github.io/aks-microservice-chart-blueprint"
