microservice-chart:
  namespace: "qi"
  nameOverride: ""
  fullnameOverride: "pagopa-qi-fdr-kpi-service"
  image:
    repository: pagopadcommonacr.azurecr.io/pagopaqifdrkpiservice
    tag: "0.1.10"
    pullPolicy: Always
  livenessProbe:
    httpGet:
      path: /actuator/health/liveness
      port: 8080
    initialDelaySeconds: 120
    failureThreshold: 6
    periodSeconds: 10
  readinessProbe:
    httpGet:
      path: /actuator/health/readiness
      port: 8080
    initialDelaySeconds: 120
    failureThreshold: 6
    periodSeconds: 10
  deployment:
    create: true
  service:
    create: true
    type: ClusterIP
    ports:
      - 8080
  ingress:
    create: true
    host: "weudev.qi.internal.dev.platform.pagopa.it"
    path: /pagopa-qi-fdr-kpi-service/(.*)
    servicePort: 8080
  serviceAccount:
    create: false
    annotations: {}
    name: ""
  podAnnotations: {}
  podSecurityContext:
    seccompProfile:
      type: RuntimeDefault
  securityContext:
    allowPrivilegeEscalation: false
  resources:
    requests:
      memory: "512Mi"
      cpu: "200m"
    limits:
      memory: "512Mi"
      cpu: "200m"
  autoscaling:
    enable: false
    minReplica: 1
    maxReplica: 1
    pollingInterval: 10 # seconds
    cooldownPeriod: 50 # seconds
    triggers:
      - type: cpu
        metadata:
          # Required
          type: Utilization # Allowed types are 'Utilization' or 'AverageValue'
          value: "75"
  envConfig:
    DEFAULT_LOGGING_LEVEL: "info"
    APP_LOGGING_LEVEL: "info"
    WEB_LOGGING_LEVEL: "info"
    ECS_SERVICE_NAME: "pagopa-qi-fdr-kpi-service"
    ECS_SERVICE_ENVIRONMENT: "dev"
    OTEL_RESOURCE_ATTRIBUTES: "service.name=pagopa-qi-fdr-kpi-service,deployment.environment=dev"
    OTEL_EXPORTER_OTLP_ENDPOINT: "http://otel-collector.elastic-system.svc:4317"
    OTEL_LOGS_EXPORTER: none
    OTEL_TRACES_SAMPLER: "always_on"
    AZURE_DATA_EXPLORER_RE_ENDPOINT: "https://pagopaddataexplorer.westeurope.kusto.windows.net"
    AZURE_DATA_EXPLORER_RE_APPLICATION_TENANT_ID: "7788edaf-0346-4068-9d79-c868aed15b3d"
  envSecret:
    OTEL_EXPORTER_OTLP_HEADERS: elastic-otel-token-header
    AZURE_DATA_EXPLORER_RE_CLIENT_ID: azure-data-explorer-re-client-id
    AZURE_DATA_EXPLORER_RE_APPLICATION_KEY: azure-data-explorer-re-application-key
  keyvault:
    name: "pagopa-d-qi-kv"
    tenantId: "7788edaf-0346-4068-9d79-c868aed15b3d"
  nodeSelector: {}
  tolerations: []
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
          - matchExpressions:
              - key: node_type
                operator: In
                values:
                  - user
  canaryDelivery:
    deployment:
      image:
        tag: ""
