microservice-chart:
  namespace: "qi"
  nameOverride: ""
  fullnameOverride: ""
  canaryDelivery:
    create: false
    ingress:
      create: true
      canary:
        type: bluegreen
    service:
      create: true
    deployment:
      create: true
      image:
        repository: pagopapcommonacr.azurecr.io/pagopaqifdrkpiservice
        tag: "latest"
        pullPolicy: Always
      envConfig: {}
  image:
    repository: pagopapcommonacr.azurecr.io/pagopaqifdrkpiservice
    tag: "0.1.2"
    pullPolicy: Always
  livenessProbe:
    handlerType: httpGet
    httpGet:
      path: /actuator/health/liveness
      port: 8080
    initialDelaySeconds: 60
    failureThreshold: 6
    periodSeconds: 10
  readinessProbe:
    handlerType: httpGet
    httpGet:
      path: /actuator/health/readiness
      port: 8080
    initialDelaySeconds: 60
    failureThreshold: 6
    periodSeconds: 10
  deployment:
    create: true
    replicas: 1
  service:
    create: true
    type: ClusterIP
    ports:
      - 8080
  ingress:
    create: true
    host: "weuprod.qi.internal.platform.pagopa.it"
    path: /pagopa-qi-fdr-kpi-service/(.*)
    servicePort: 8080
  serviceAccount:
    create: false
    annotations: {}
    name: ""
  podAnnotations: {}
  podSecurityContext:
    seccompProfile:
      type: RuntimeDefault
  securityContext:
    allowPrivilegeEscalation: false
  resources:
    requests:
      memory: "512Mi"
      cpu: "200m"
    limits:
      memory: "512Mi"
      cpu: "200m"
  autoscaling:
    enable: true
    minReplica: 1
    maxReplica: 5
    pollingInterval: 30 # seconds
    cooldownPeriod: 30 # seconds
    triggers:
      - type: cpu
        metadata:
          # Required
          type: Utilization # Allowed types are 'Utilization' or 'AverageValue'
          value: "70"
    advanced:
      horizontalPodAutoscalerConfig:
        behavior:
          scaleUp:
            stabilizationWindowSeconds: 60
  envConfig:
    DEFAULT_LOGGING_LEVEL: "info"
    APP_LOGGING_LEVEL: "info"
    WEB_LOGGING_LEVEL: "info"
    ECS_SERVICE_NAME: "pagopa-qi-fdr-kpi-service"
    ECS_SERVICE_ENVIRONMENT: "dev"
    OTEL_RESOURCE_ATTRIBUTES: "service.name=pagopa-qi-fdr-kpi-service,deployment.environment=prod"
    OTEL_EXPORTER_OTLP_ENDPOINT: "http://otel-collector.elastic-system.svc:4317"
    OTEL_LOGS_EXPORTER: none
    OTEL_TRACES_SAMPLER: "always_on"
    AZURE_DATA_EXPLORER_RE_ENDPOINT: "https://pagopapdataexplorer.westeurope.kusto.windows.net"
    AZURE_DATA_EXPLORER_RE_APPLICATION_TENANT_ID: "7788edaf-0346-4068-9d79-c868aed15b3d"
  envSecret:
    AZURE_DATA_EXPLORER_RE_CLIENT_ID: azure-data-explorer-re-client-id
    AZURE_DATA_EXPLORER_RE_APPLICATION_KEY: azure-data-explorer-re-application-key
  keyvault:
    name: "pagopa-p-qi-kv"
    tenantId: "7788edaf-0346-4068-9d79-c868aed15b3d"
  nodeSelector: {}
  tolerations: []
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
          - matchExpressions:
              - key: node_type
                operator: In
                values:
                  - user
